image: "python:3.7"

variables:
  MPLBACKEND: "agg"

code_analysis:
  stage: build
  before_script:
    - pip install pylint pylint-json2html
  script:
    - mkdir -p code_analysis
    - pylint -j 0 --extension-pkg-whitelist=numpy --ignored-classes=astropy.units,astropy.constants,HDUList -f json -E rascil tests | pylint-json2html -o code_analysis/index.html
  artifacts:
    paths:
      - code_analysis
    expire_in: 1 week

docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - pip install -r requirements.txt -r requirements-docs.txt
    - mkdir -p docs/build/html
  script:
    - export PYTHONPATH=`pwd`
    - echo $PYTHONPATH
    - PYTHONPATH=`pwd` make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

unittests:
  stage: build
  before_script:
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - pip install pytest pytest-xdist pytest-cov
    - py.test -n 4 tests --verbose --cov=rascil --cov-report=html:coverage
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - docs
    - unittests
    - code_analysis
  script:
    - mv html public
    - mv coverage/ public/coverage
    - mv code_analysis/ public/code_analysis
  artifacts:
    paths:
      - public
      - public/coverage
      - public/code_analysis
    expire_in: 1 month
  only:
    - master
