image: "python:3.7"

variables:
  MPLBACKEND: "agg"

data:
  stage: build
  script:
    - tar -zcf rascil_data.tgz data
  after_script:
  artifacts:
    paths:
      - rascil_data.tgz
    expire_in: 6 months

docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - pip install -r requirements.txt -r requirements-doc.txt
    - mkdir -p docs/build/html
    - mkdir -p test_results
  script:
    - PYTHONPATH=`pwd` HOME=`pwd` make -k -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

unittests:
  stage: build
  before_script:
    - pip install -r requirements.txt
  script:
    - pip install pytest pytest-xdist pytest-cov
    - HOME=`pwd` py.test tests/workflows/test*rsexecute.py --verbose --cov=rascil --cov-report=html:coverage --durations=30 --forked
    - HOME=`pwd` py.test -n 4 tests/data_models tests/processing_components tests/workflows/test*serial.py --verbose --cov=rascil --cov-report=html:coverage --cov-append --durations=30 --forked
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - docs
    - unittests
    - data
  script:
    - mv html public
    - mv rascil_data.tgz public
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
      - public/coverage
    expire_in: 1 month
  only:
    - master
