image: python:3.7

variables:
  MPLBACKEND: "agg"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - linting
  - test
  - build
  - publish
  - prepost

compile_requirements:
  only:
    - schedules
  variables:
    GIT_LFS_SKIP_SMUDGE: "1"  # do not download LFS related files
  before_script:
    - apt-get -y update
    - apt-get -y install git-lfs
    - git lfs fetch --all  # without this, the job complains about not finding a file, that doesn't actually exist..
    - pip3 install --upgrade pip
    - pip install gitpython python-gitlab
    - pip install importlib-metadata numpy  # importlib-metadata is needed for python<=3.7; numpy is needed for bdsf
    - make requirements
  script:
    - python3 create_mr.py

linting:
  except:
    - schedules
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  stage: linting
  before_script:
    - pip3 install -r requirements-test.txt
    - pip3 install black
  script:
    - make lint
  when: always
  artifacts:
    paths:
      - linting.xml

# Always run the unittests
test:
  except:
    - schedules
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install rsync ca-certificates pybind11-dev
    - pip3 install -r requirements-test.txt
    - pip3 install -r requirements.txt
    - mkdir -p /usr/share/casacore/data/
    - cd /usr/share/casacore/data
    - wget -O WSRT_Measures.ztar ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
    - tar xfz WSRT_Measures.ztar
    - cd -
#    - rsync -avz4 rsync://casa-rsync.nrao.edu/casa-data/geodetic /usr/share/casacore/data/
    - mkdir -p test_results
  script:
    - PYTHONPATH=`pwd` HOME=`pwd` make test
  after_script:
    - mv .coverage coverage_test
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    paths:
      - coverage_test
      - coverage
      - unit-tests-other.xml

test-dask:
  except:
    - schedules
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install rsync ca-certificates pybind11-dev
    - pip3 install -r requirements-test.txt
    - pip3 install -r requirements.txt
    - mkdir -p /usr/share/casacore/data/
    - cd /usr/share/casacore/data
    - wget -O WSRT_Measures.ztar ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
    - tar xfz WSRT_Measures.ztar
    - cd -
    - mkdir -p test_results
  script:
    - PYTHONPATH=`pwd` HOME=`pwd` make test-dask
  after_script:
    - mv .coverage coverage_dask
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    paths:
      - coverage_dask
      - coverage
      - unit-tests-dask.xml

# Always try to build the docs since this catches errors via the notebook
docs:
  except:
    - schedules
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install pandoc rsync
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - mkdir -p docs/build/html
    - mkdir -p test_results
    - mkdir -p /usr/share/casacore/data/
    - cd /usr/share/casacore/data
    - wget -O WSRT_Measures.ztar ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
    - tar xfz WSRT_Measures.ztar
    - cd -
  script:
    - PYTHONPATH=`pwd` HOME=`pwd` make docs
  artifacts:
    paths:
      - docs/build/html/
    expire_in: 1 week

# Build the data file only if on the master
data:
  stage: build
  script:
    - tar -zcf rascil_data.tgz data
  artifacts:
    paths:
      - rascil_data.tgz
    expire_in: 6 months
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

# Publish package to Central Artefact Repository only if this is a tagged build of the master
publish_to_car:
  stage: publish
  image: $SKA_K8S_TOOLS_DEPLOY_IMAGE
  script:
    - echo "Commit tag is ${CI_COMMIT_TAG}"
    - echo "Commit message is ${CI_COMMIT_MESSAGE}"
    - python3 setup.py egg_info sdist bdist_wheel # --universal option to used for pure
    - /usr/local/bin/extract-metadata.sh MANIFEST.skao.int
    - for filename in dist/*.whl dist/*.tar.gz; do
    -   /usr/local/bin/patch-metadata.sh $filename MANIFEST.skao.int
    - done
    - TWINE_USERNAME=${CAR_PYPI_USERNAME} TWINE_PASSWORD=${CAR_PYPI_PASSWORD} twine upload --repository-url $CAR_PYPI_REPOSITORY_URL dist/*
  rules:
    - if: '$CI_COMMIT_TAG'
    # - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

# Trigger downstream docker build to nexus only if this is build of the master,
# Pass the tag downstream so that the build can be marked stable if this is tagged
staging: # Start the construction of dockers files in rascil-docker
  stage: publish
  variables:
    UPSTREAM_TAG: $CI_COMMIT_TAG
  trigger: ska-telescope/external/rascil-docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

# Publish the docs, data, and coverage if this is a build of the master
pages:
  stage: publish
  dependencies:
    - docs
    - test
    - data
  script:
    - rm -rf public
    - mkdir -p public
    - mv docs/build/html/* public
    - mv coverage public
    - mv rascil_data.tgz public
    - ls -l public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

prepare ci metrics:
  except:
    - schedules
  stage: prepost
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  when: always
  before_script:
    - mkdir -p build/reports
    - coverage combine coverage_* && coverage xml && coverage html -d coverage && coverage report
    - test -a coverage.xml && mv coverage.xml ./build/reports/code-coverage.xml
    - test -a linting.xml && mv linting.xml ./build/reports/linting.xml
    - python3 util/xmlcombine.py unit-tests-dask.xml unit-tests-other.xml > unit-tests.xml
    - test -a unit-tests.xml && mv unit-tests.xml ./build/reports/unit-tests.xml
  script:
    # Gitlab CI badges creation: START
    # The following reads::
    # build/reports/code-coverage.xml
    # build/reports/unit-tests.xml
    # build/reports/linting.xml
    # And writes:
    # build/reports/ci-metrics.json
    - apt-get -y update
    - apt-get install -y curl --no-install-recommends
    - curl -s https://gitlab.com/ska-telescope/ci-metrics-utilities/raw/master/scripts/ci-badges-func.sh | sh
    # Gitlab CI badges creation: END
  artifacts:
    paths:
      - coverage
      - ./build

# Create Gitlab CI badges from CI metrics
# https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'
