image: python:3.7

variables:
  MPLBACKEND: "agg"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - build
  - publish

# Always run the unittests. Add retry since the rsync is currently unreliable
unittests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install rsync ca-certificates pybind11-dev
    - pip3 install -r requirements.txt
    - mkdir -p /usr/share/casacore/data/
    - rsync -avz4 rsync://casa-rsync.nrao.edu/casa-data/geodetic /usr/share/casacore/data/
    - git clone https://gitlab.mpcdf.mpg.de/ift/nifty_gridder.git
    - cd nifty_gridder
    - pip3 install .
    - cd ..
    - mkdir -p test_results
  script:
    - pip3 install pytest pytest-xdist pytest-cov
    - HOME=`pwd` py.test tests/workflows/test*rsexecute.py --verbose --cov=rascil --cov-report=html:coverage   --durations=30 --forked
    - HOME=`pwd` py.test -n 4 tests/data_models tests/processing_components tests/workflows/test*serial.py --verbose  --cov=rascil --cov-report=html:coverage --cov-append --durations=30 --forked
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

# Always try to build the docs since this catches errors via the notebook
docs:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install pandoc rsync
    - pip install -r requirements.txt -r requirements-docs.txt
    - mkdir -p docs/build/html
    - mkdir -p test_results
    - mkdir -p /usr/share/casacore/data/
    - rsync -avz4 rsync://casa-rsync.nrao.edu/casa-data/geodetic /usr/share/casacore/data/
  script:
    - PYTHONPATH=`pwd` HOME=`pwd` make -k -C docs/src html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

# Build the data file only if on the master
data:
  stage: build
  script:
    - tar -zcf rascil_data.tgz data
  artifacts:
    paths:
      - rascil_data.tgz
    expire_in: 6 months
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# Publish pip file to nexus only if this is a tagged build of the master
publish_to_nexus:
  stage: publish
  tags:
    - docker-executor
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - echo "Commit tag is ${CI_COMMIT_TAG}"
    - echo "Commit message is ${CI_COMMIT_MESSAGE}"
    - pip3 install setuptools
    - python3 setup.py egg_info sdist bdist_wheel # --universal option to used for pure
    - pip3 install twine
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/*
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "master"'

# Trigger downstream docker build to nexus only if this is a tagged build of the master
staging: # Start the construction of dockers files in rascil-docker
  stage: publish
  trigger: ska-telescope/rascil-docker
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "master"'

# Publish the docs, data, and coverage if this is a build of the master
pages:
  stage: publish
  dependencies:
    - docs
    - unittests
    - data
  script:
    - mv html public
    - mv rascil_data.tgz public
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
      - public/coverage
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
