image: "python:3.7"

stages:
  - test

variables:
  MPLBACKEND: "agg"

docs:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install pandoc
    - pip install -r requirements.txt -r requirements-docs.txt
    - mkdir -p docs/build/html
  script:
    - export PYTHONPATH=`pwd`
    - echo $PYTHONPATH
    - PYTHONPATH=`pwd` make -k -j -C docs html
  after_script:
    - mv docs/build/html html
  artifacts:
    paths:
      - html/
    expire_in: 1 week

test:
  stage: test
  before_script:
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - echo $RASCIL
    - pip install pytest pytest-xdist pytest-cov
    - py.test -n 4 tests --verbose --cov=rascil --cov-report=html:coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week

