# PersistentVolume and Claim to mount data which can be used by Dask workers
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-rascil-cip
#  labels:
#    type: manual
spec:
  storageClassName: nfss1 #manual
#  claimRef:
#    name: pvc-rascil-cip
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/builds/ska-telescope/external/rascil/docker/kubernetes/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rascil-cip
spec:
  storageClassName: nfss1 #manual
  volumeName: pv-rascil-cip
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
#  selector:
#    matchLabels:
#      type: manual